### ISSUE TITLE
Typo on readme.md

### ISSUE THREAD

**Issue by rasanentimo** [kkthxbye-code/netbox-script-manager#4]
There's a typo on the readme.md. 

I suppose this

```
PLUGINS_CONFIG = {
    "netbox_script_manager Manager": {
        "SCRIPT_ROOT": "/path/to/script/folder/",
        "DEFAULT_QUEUE": "high"
    },
}
```

is supposed to be 

```
PLUGINS_CONFIG = {
    "netbox_script_manager": {
        "SCRIPT_ROOT": "/path/to/script/folder/",
        "DEFAULT_QUEUE": "high"
    },
}
```

**Comment by kkthxbye-code** [comment]
It was indeed a typo.

You created your PR against your own fork instead of this one, so I fixed it in https://github.com/kkthxbye-code/netbox-script-manager/commit/b5173ab8c0504ad4e2ca4510532befe2b8f491d4.

Thank you!-
